In [1]:
# settings local:
%run "../../../common/0_notebooks_base_setup.py"   

C:\Users\Charl\OneDrive\Desktop\Digital-House\clase_03\dsad_2021\common
default checking
Running command `conda list`... error
    'conda' is not recognized as an internal or external command,
operable program or batch file.



---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


En la práctica de la clase de hoy usaremos un dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

Ustedes tienen un subconjunto de los datos disponibles, que usaremos para resolver ejercicios de Numpy.

## Ejercicio 1

Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [2]:
import numpy as np

path = '../Data/sales_data_sample_excercise.csv'
np.genfromtxt(path, skip_header = 1 ,delimiter = '\t', dtype = str)

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [3]:
#Si lo intentamos leer tipo int, trunca los floats a tipo entero, y los str, les asigna -1
import numpy as np

path = '../Data/sales_data_sample_excercise.csv'
np.genfromtxt(path, skip_header = 1 ,delimiter = '\t', dtype = int) 

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,  2765,     5,  2003,    -1,    -1],
       [10134,  3884,     7,  2003,    -1,    -1],
       ...,
       [10386,  5417,     3,  2005,    -1,    -1],
       [10397,  2116,     3,  2005,    -1,    -1],
       [10414,  3079,     5,  2005,    -1,    -1]])

In [4]:
import numpy as np

path = '../Data/sales_data_sample_excercise.csv'
np.genfromtxt(path, skip_header = 1 ,delimiter = '\t', dtype = float) 

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

## Ejercicio 2

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [5]:
import numpy as np

path = '../Data/sales_data_sample_excercise.csv'
file = np.genfromtxt(path, skip_header = 1 ,delimiter = '\t', dtype = str) 
#Sales es columna 2, todas las filas y Country, es columna 6, todas las filas
Sales_vector_str = file[:,1]
Country_vector_str = file[:,5]
sales_numeric = (Sales_vector_str).astype(float)
print(sales_numeric)
print(Country_vector_str)

[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


## Ejercicio 3

¿Cuál fue el monto mínimo de una venta? ¿Cuál fue el monto máximo?

In [6]:
np.min(sales_numeric)

482.13

In [7]:
np.max(sales_numeric)

14082.8

## Ejercicio 4

¿Cuántas ventas se hicieron en Spain?

Ayuda: boolean indexing


In [8]:
condicion = Country_vector_str =='Spain'
sales_numeric[condicion].shape[0]

342

## Ejercicio 5

¿Qué porcentaje de las ventas se hicieron en Spain?


In [9]:
percentageOfSales = sales_numeric[condicion].shape[0] / sales_numeric.shape[0] * 100


## Ejercicio 6

¿Cuál es el país de la venta de precio máximo? ¿Cuál es el id de esa venta?

Ayuda: boolean indexing

In [10]:
maxPrice = 14082.8
mask = sales_numeric == maxPrice

print(Country_vector_str[mask])
print(file[:,0][mask])

['USA']
['10407']


## Ejercicio 7

¿Cuál es el precio promedio de ventas en France? ¿Cuál es el desvío?

In [11]:
condicion = Country_vector_str =='France'
print(np.mean(sales_numeric[condicion]))
print(np.std(sales_numeric[condicion]))

3537.9507006369427
1939.214360481481


## Ejercicio 8

¿Cuál fue el año con máximo desvío en las ventas en France?

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

In [22]:
print((np.unique(file[:,3])).astype(float))
#saco el desvio de cada año
aniosTofloat = file[:,3].astype(float)
listaAnios = [2003,2004,2005]
lista=[]
for anios in listaAnios:
    lista.append(np.std(sales_numeric[aniosTofloat == anios]))

max(lista)
 

[2003. 2004. 2005.]


2149.5467692849306