In [1]:
# initial setup
%run "../../../common/0_notebooks_base_setup.py"


/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


In [21]:
import pandas as pd
import numpy as np

<link rel="stylesheet" href="../../../common/dhds.css">
<div class="Table">
    <div class="Row">
        <div class="Cell grey left"> <img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_portada.jpg" align="center" width="90%"/></div>
        <div class="Cell right">
            <div class="div-logo"><img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/common/logo_DH.png" align="center" width=70% /></div>
            <div class="div-curso">DATA SCIENCE</div>
            <div class="div-modulo">MÓDULO 4</div>
            <div class="div-contenido">Naive Bayes</div>
        </div>
    </div>
</div>

## Agenda

---

- Identificar casos de uso: como benchmark y como clasificador eficiente

- Probabilidad Condicional. Teorema de Bayes. Independencia.

- Conocer el funcionamiento del algoritmo Naive Bayes

- Implementar el modelo y evaluar la performance



<div class="div-dhds-fondo-1"> Introducción
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_separador.png" align="center" />

</div>

<img src="Bayes_1.png"/>

<img src="Bayes_3.png"/>

<img src="Bayes_4.png"/>

<img src="Bayes_5.png"/>

<img src="Bayes_6.png"/>

<img src="Bayes_7.png"/>

Volviendo al planteo inicial

<img src="Bayes_8.png"/>

Comparación

<img src="Bayes_9.png"/>

<img src="Bayes_10_b.png"/>

Formula

<img src="Bayes_11.png"/>

<img src="Bayes_12_a.png"/>

## ¿Qué es Naive Bayes?

---

**Naive Bayes es uno de los algoritmos más simples de clasificación basado en el teorema de Bayes con un supuesto de independencia entre los predictores.**

El modelo Naive Bayes es fácil de construir y particularmente útil para conjuntos de datos muy grandes. 

Es "ingenuo" porque **asume que cualquier feature no está relacionada con ninguna otra feature**. Incluso si estas features dependen unas de otras o de la existencia de otras features, todas estas propiedades contribuyen de forma independiente a la probabilidad de que una instancia pertenezca a una clase.

## ¿Cuándo usarlo?

---

Los clasificadores basados en Naive Bayes hacen fuertes supuestos sobre los datos, así que no van a tener tan buena performance si el verdadero proceso generador de los datos no cumple con los supuestos de Naive Bayes. 

Dicho esto, tienen las siguientes ventajas:

* Son algoritmos **muy rápidos** tanto para entrenar como para predecir

* Brindan una **predicción probabilística** (tenemos probabilidades para cada clase)

* Son **sencillos de interpretar**

* No requieren "tunear" ningún hiperparámetro


## Naive Bayes como baseline

---

Dado que Naive Bayes es tan fácil de optimizar y tan rápido desde el punto de vista computacional, es un buen **"baseline"** para un problema de clasificación. 

Si performa bien, podemos quedarnos con este modelo y si necesitamos mejorar la precisión, tenemos una línea de base sobre la cual mejorar.

Naive Bayes tiende a funcionar bien en las siguientes situaciones:

- **Cuando se cumplen los supuestos** (cosa que rara vez pasa en casos reales)

- **Cuando las clases están muy bien separadas** y no es necesaria tanta complejidad en el modelo. 

- **Cuando tenemos datos con muy alta dimensionalidad** (por ejemplo text mining) donde la complejidad del modelo también es menos importante porque hay mucha información para cada observación. 

Los distintos algoritmos de Naive Bayes difieren en la distribución que suponen para $P(x_i|y)$

* **Gaussian Naive Bayes**: Supone distribución Gaussiana multidimensional

* **Multinomial Naive Bayes**: Supone distribución multinomial. 

<div class="div-dhds-fondo-1"> Gaussian Naive Bayes
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_separador.png" align="center" />

</div>

## Gaussian Naive Bayes

---

Un modelo de tipo "Gaussian Naive Bayes" toma datos como los que se ven abajo y calcula una distribución para cada una de las clases. 

Para cada nuevo punto que queremos clasificar obtenemos un valor de probabilidad de pertenecer a cada una de las clases.

En este clasificador, **la suposición es que los datos de cada etiqueta se extraen de una distribución gaussiana multivariada donde las features son independientes entre sí**


<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_naive_bayes.png" align="center" />






## Gaussian Naive Bayes - Ejemplo

---


<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_gaussian_naive_bayes.png" align="center" />




Distribución Gaussiana Multivariada: 


<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_gaussiana_multivariada.png" align="center" />

<p style="font-size:24px;">
$X \sim N(\mu, \Sigma)$
</p>    

$\Sigma$ es la matriz de covarianzas de las componentes $X_i$

Naive Bayes supone que cada una de las clases proviene de una distribución Gaussiana multivariada donde **las features son independientes** entre sí.

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_gaussiana_normal_multivariada.png" align="center" />


EJEMPLO: Personas a las que les gusta la pelicula Troll 2

<img src='Bayes_13.png'/>


<img src='Bayes_14.png'/>


Distribución de consumo de pochoclo para clase Verde

<img src='Bayes_15.png'/>


Distribución pochoclo para clase roja

<img src='Bayes_16.png'/>


Las 3 distribuciones, para las 2 clases

<img src='Bayes_17.png'/>


* Viene una nueva observación con las siguientes features
  - 20 gramos de pochoclo. 
  - 500 ml de soda
  - 25 gramos de caramelo

<img src='Bayes_18.png'/>


Probabilidad de las features, dado el label

<img src='Bayes_20.png'/>


<img src='Bayes_21.png'/>


<img src='Bayes_22.png'/>


<img src='Bayes_23.png'/>


<img src='Bayes_24.png'/>


<img src='Bayes_25.png'/>


<img src='Bayes_26.png'/>


<img src='Bayes_27.png'/>


<img src='Bayes_28.png'/>


<img src='Bayes_29.png'/>


<img src='Bayes_30.png'/>


Como Hands-on vamos a resolver un problema de clasificación usando Gaussian Naive Bayes

<div class="div-dhds-fondo-1"> Multinomial Naive Bayes
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_separador.png" align="center" />

</div>

### Multinomial Naive Bayes

---

En este clasificador se supone que las features tienen distribución multinomial simple. 

La distribución multinomial describe la probabilidad de observar recuentos entre varias categorías y, por lo tanto, naive bayes multinomial es más apropiado para las features que representan recuentos o tasas de recuento.

La idea es exactamente la misma que antes, excepto que en lugar de modelar la distribución de datos con la distribución gaussiana de mejor ajuste, modelamos la distribución de datos con una distribución multinomial de mejor ajuste.


## Multinomial Naive Bayes - Ejemplo

---

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_ejemplo_mails_naive_bayes.png" align="center" />




A continuación vamos a entrenar un modelo de clasificación **Multinomial Naive Bayes** para predecir si un texto corresponde a un email de spam o no.

El dataset original (<a href="https://www.kaggle.com/riyadhrazzaq/multinomial-naive-bayes-from-scratch/data?select=spam.csv" traget="_blank">fuente</a>) tiene dos columnas: el texto del email y la etiqueta que queremos predecir (spam o ham).

El dataset que vamos a usar en este ejercicio es una trasnformación del original:

* Tiene 8682 columnas, cada una de ellas es una palabra que apareció en el campo texto del email, en alguno de los registros del dataset original. 

* El valor en el dataframe de cada elemento (i, j) corresponde a la cantidad de veces que aparece la palabra j en el mensaje i.


In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB

Leemos los datos desde un archivo .zip

In [23]:
data = pd.read_csv('../Data/spam_count_vectorizer.zip', sep='\t')
data.shape

(5572, 8682)

In [5]:
data.head(5)

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0   0    0       0             0     0     0            0            0   
1   0    0       0             0     0     0            0            0   
2   0    0       0             0     0     0            0            0   
3   0    0       0             0     0     0            0            0   
4   0    0       0             0     0     0            0            0   

   0125698789  02  ...  ûṫm  ûṫre  ûṫs  ûṫt  ûṫve  ûẃm  ûẃt  ûẃve  ûỳud  \
0           0   0  ...    0     0    0    0     0    0    0     0     0   
1           0   0  ...    0     0    0    0     0    0    0     0     0   
2           0   0  ...    0     0    0    0     0    0    0     0     0   
3           0   0  ...    0     0    0    0     0    0    0     0     0   
4           0   0  ...    0     0    0    0     0    0    0     0     0   

   target  
0     ham  
1     ham  
2    spam  
3     ham  
4     ham  

[5 rows x 8682 columns]

Creamos la matriz de features y el vector target.

In [26]:
y = data['target']
X = data.iloc[:, range(data.shape[1]-1) ]
X.head(5)

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0   0    0       0             0     0     0            0            0   
1   0    0       0             0     0     0            0            0   
2   0    0       0             0     0     0            0            0   
3   0    0       0             0     0     0            0            0   
4   0    0       0             0     0     0            0            0   

   0125698789  02  ...  ûṫll  ûṫm  ûṫre  ûṫs  ûṫt  ûṫve  ûẃm  ûẃt  ûẃve  ûỳud  
0           0   0  ...     0    0     0    0    0     0    0    0     0     0  
1           0   0  ...     0    0     0    0    0     0    0    0     0     0  
2           0   0  ...     0    0     0    0    0     0    0    0     0     0  
3           0   0  ...     0    0     0    0    0     0    0    0     0     0  
4           0   0  ...     0    0     0    0    0     0    0    0     0     0  

[5 rows x 8681 columns]

Vemos la proporción de cada una de las etiquetas en el dataframe.

In [29]:
y.value_counts(normalize=True)

ham     0.865937
spam    0.134063
Name: target, dtype: float64

Creamos los conjuntos de entrenamiento y testing

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state = 12)

Instanciamos el modelo y lo entrenamos con los datos de train

In [31]:
model = MultinomialNB()
model.fit(X_train, y_train)


MultinomialNB()

Evaluamos accuracy en test

In [32]:
model.score(X_test, y_test)

0.9806173725771715

Calculamos la matriz de confusión

In [33]:
y_hat = model.predict(X_test)
y_hat

array(['spam', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [34]:
confusion_matrix(y_test, y_hat)

array([[1189,   17],
       [  10,  177]])

Para saber qué columna corresponde a cada categoría usamos `classes_`

In [13]:
model.classes_

array(['ham', 'spam'], dtype='<U4')

Podemos usar `predict_proba` para ver qué probabilidad tiene cada registro en cada clase

In [14]:
model.predict_proba(X_test)

array([[3.43338248e-14, 1.00000000e+00],
       [9.99999997e-01, 3.20567013e-09],
       [1.00000000e+00, 6.88321161e-14],
       ...,
       [9.99999987e-01, 1.33455628e-08],
       [9.99999988e-01, 1.24077729e-08],
       [1.00000000e+00, 5.32109489e-14]])

Y vemos que la suma de cada fila da 1 (para cada registro la suma de las probabilidades de pertenecer a la clase spam o a la clase ham es 1)

Por un tema de redondeo vemos que la suma no siempre da 1, entonces vamos a usar como prueba que no haya ningún registro cuya suma difiera de 1 en más de 0.00001

In [15]:
any(model.predict_proba(X_test).sum(axis=1) != 1)

True

In [16]:
any(abs(model.predict_proba(X_test).sum(axis=1)-1) > 1e-5)


False

## Naive Bayes: problemas con el caso discreto

---

Algunos problemas que puede presentar el caso discreto:
    
* **Problema de frecuencia cero**:
    
Por ejemplo, en el caso anterior, cualquier mail que contenga la palabra “account” va a ser considerado spam porque P(account/ham)=0/2.

Solución: agregar un pequeño valor positivo al conteo (**Laplace smoothing**): 

<p style="font-size=24px;">
    
$$P(word|label) = \frac{count(word | label) + alpha} {count(label) + 2*alpha}$$
    
</p>

- **Asume independencia de las features** (en nuestro ejemplo, palabras):
    
Se puede engañar al clasificador agregando muchas palabras asociadas con mail “no spam” a un mail de “spam” 


<div class="div-dhds-fondo-1"> Hands-on
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_separador.png" align="center" />

</div>

## Ejercicio

---


Vamos a usar un dataset de vinos que descargamos de https://archive.ics.uci.edu/ml/datasets/Wine para intentar predecir de qué categoria es (campo quality).

Estos datos son el resultado de un análisis químico de vinos cultivados en la misma región en Italia pero derivados de tres variedades diferentes. El análisis determinó las cantidades de 13 componentes encontrados en cada uno de los tres tipos de vinos.

Las categorías están codificadas como 1, 2 y 3 corresponden a calidad alta, media, o baja. 

Entrenemos un modelo de clasificación <a href= "https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html" target= "_blank"> Gaussian Naive Bayes</a> para predecir el valor `quality` y evaluemos el valor de accuracy y la matriz de confusión en el conjunto de test.


In [17]:
data_columns = ['quality', 'alcohol', 'malic_acid', 'ash', 
                'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids',
                'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 
                'hue', 'OD280_OD315_of_diluted_wines', 'proline']

data = pd.read_csv("../Data/wine.data", header = None)

data.columns = data_columns

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   quality                       178 non-null    int64  
 1   alcohol                       178 non-null    float64
 2   malic_acid                    178 non-null    float64
 3   ash                           178 non-null    float64
 4   alcalinity_of_ash             178 non-null    float64
 5   magnesium                     178 non-null    int64  
 6   total_phenols                 178 non-null    float64
 7   flavanoids                    178 non-null    float64
 8   nonflavanoid_phenols          178 non-null    float64
 9   proanthocyanins               178 non-null    float64
 10  color_intensity               178 non-null    float64
 11  hue                           178 non-null    float64
 12  OD280_OD315_of_diluted_wines  178 non-null    float64
 13  proli

In [18]:
data.quality.unique()

array([1, 2, 3])

## Solución

---

Creamos los conjuntos de entrenamiento y test

In [19]:
X = data.drop(['quality'], axis=1)
Y = data['quality']

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 1237)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(124, 13)
(54, 13)
(124,)
(54,)


Instanciamos el clasificador Gaussian Naive Bayes y lo entrenamos con los datos de train

In [21]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, Y_train)

GaussianNB()

Con el modelo entrenado predecimos los valores de quality en los datos de test

In [22]:
Y_pred = gnb.predict(X_test)

Y_pred

array([2, 1, 3, 1, 3, 1, 2, 3, 2, 2, 2, 1, 2, 1, 1, 3, 1, 3, 2, 2, 2, 1,
       2, 2, 1, 3, 2, 3, 3, 3, 1, 1, 3, 1, 3, 3, 3, 3, 1, 2, 3, 3, 2, 1,
       3, 2, 2, 3, 2, 3, 2, 2, 2, 2])

Evaluamos el valor de accuracy y la matriz de confusión en el conjunto de test

In [23]:
round(accuracy_score(Y_test, Y_pred), 2)

0.94

In [24]:
conf_mat = confusion_matrix(Y_test, Y_pred)

print('Confusion matrix\n\n', conf_mat)


Confusion matrix

 [[14  1  0]
 [ 0 20  2]
 [ 0  0 17]]


<div class="div-dhds-fondo-1"> Referencias y Material Adicional
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M4/CLASE_29_Naive_Bayes/Presentacion/img/M4_CLASE_29_separador.png" align="center" />

</div>

## Referencias

---

<a href="https://towardsdatascience.com/all-about-naive-bayes-8e13cef044cf" target="_blank">All about Naive Bayes</a>

<a href="https://www.kaggle.com/mgmarques/wines-type-and-quality-classification-exercises" target="_blank">Wines type and quality classification exercises</a>

<a href="https://www.kaggle.com/riyadhrazzaq/multinomial-naive-bayes-from-scratch/data" target="_blank">Multinomial Naive Bayes from scratch</a>

<a href="https://towardsdatascience.com/naive-bayes-classifier-explained-54593abe6e18" target="_blank">Naive Bayes Classifier Explained</a>

<a href="https://towardsdatascience.com/laplace-smoothing-in-na%C3%AFve-bayes-algorithm-9c237a8bdece" target="_blank">Laplace smoothing in Naïve Bayes algorithm</a>

Python Data Science Handbook. Jake VanderPlas. Cap 5.

- <a href="https://jakevdp.github.io/PythonDataScienceHandbook/05.05-naive-bayes.html" target="_blank">https://jakevdp.github.io/PythonDataScienceHandbook/05.05-naive-bayes.html</a>

- <a href="https://github.com/jakevdp/PythonDataScienceHandbook/tree/master/notebooks" target="_blank">https://github.com/jakevdp/PythonDataScienceHandbook/tree/master/notebooks</a>

- <a href="https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.05-Naive-Bayes.ipynb" target="_blank">https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.05-Naive-Bayes.ipynb</a>




StatQuest

- <a href="https://www.youtube.com/watch?v=O2L2Uv9pdDA" target="_blank">https://www.youtube.com/watch?v=O2L2Uv9pdDA</a>

- <a href="https://www.youtube.com/watch?v=pYxNSUDSFH4" target="_blank">https://www.youtube.com/watch?v=pYxNSUDSFH4</a>

- <a href="https://www.youtube.com/watch?v=H3EjCKtlVog" target="_blank">https://www.youtube.com/watch?v=H3EjCKtlVog</a>
