In [2]:
# Ejercicio 1
# Dada la instancia de NumPy array

# data = np.array([[0, 1, 2, 3, 4], 
#               [2, 3, 5, 6, 7], 
#               [5, 6, 7, 8, 9], 
#               [10, 11, 12, 13, 14], 
#               [15, 16, 17, 18, 19], 
#               [1, 2, 3, 4, 5]
#              ])

# Obtener un array que tenga sólo las filas impares de 'data' usando:

# Slicing:

# Fancy indexing

# El resultado debe ser

# np.array([[0, 1, 2, 3, 4], 
#     [5, 6, 7, 8, 9], 
#     [15, 16, 17, 18, 19]])

In [3]:
import numpy as np

data = np.array ([[0, 1, 2, 3, 4], 
                  [2, 3, 5, 6, 7], 
                  [5, 6, 7, 8, 9], 
                  [10, 11, 12, 13, 14], 
                  [15, 16, 17, 18, 19], 
                  [1, 2, 3, 4, 5]
                 ])
odd_rows = data[1:6:2,:]
print(odd_rows)
print()
fancy_list = [1,3,5]
fancy_odd_rows = data[fancy_list,:]
print(fancy_odd_rows)

[[ 2  3  5  6  7]
 [10 11 12 13 14]
 [ 1  2  3  4  5]]

[[ 2  3  5  6  7]
 [10 11 12 13 14]
 [ 1  2  3  4  5]]


In [4]:
# Ejercicio 2
# Seleccionar los elementos de valor par de 'data' usando boolean indexing

In [5]:
condition = data % 2 == 0

print(data[condition])
print()
print(np.where(condition, data, 0))

[ 0  2  4  2  6  6  8 10 12 14 16 18  2  4]

[[ 0  0  2  0  4]
 [ 2  0  0  6  0]
 [ 0  6  0  8  0]
 [10  0 12  0 14]
 [ 0 16  0 18  0]
 [ 0  2  0  4  0]]
